#!/bin/sh
prev=""
sum=0
while read count word; do
    if [[ $word != $prev ]]; then
        [[ $prev != "" ]] && printf "% 8d %s\n" $sum $prev
        sum=$count
        prev=$word
    else
        sum=`expr $sum + $count`
    fi
done
printf "% 8d %s\n" $sum $prev
