#!/bin/sh

# date
# time
# number
# email
# url
# ignore case
# unecessary mark
# alignment
sed \
    -e "s/[0-9]\{4\}[-/][0-9]\{1,2\}[-/][0-9]\{1,2\}/\$\{date\} /g" \
    -e "s/\(20\|21\|22\|23\|[0-1][0-9]\):[0-5][0-9]:[0-5][0-9]/\$\{time\} /g" \
    -e "s/[0-9]\+\([-,.:][0-9]\+\)\{0,\}/\$\{number\} /g" \
    -e "s/\w\+@\w\+\.\w\+/\$\{email\} /g" \
    -e "s/[a-zA-Z]\+:\/\/[^ ]\+/\$\{url\} /g" \
    -e "y/ABCDEFGHICKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/" \
    -e "s/\(=\{3,\}\|-\{3,\}\|\*\+\)//g" \
    -e "s/[,;.]/\n/g" |

# trim space & remove empty line
sed -e "s/\(^[ \t]\+\|[ \t]\+$\)//g" -e "s/[ \t]\{2,\}/ /g" -e "/^$/d"

